# ABOUTME: Generates THIRD-PARTY-NOTICES for the Rust crates (and the BoringSSL copy vendored by
# ABOUTME: boring-sys) statically linked into libenso_quiche, from a locked quiche checkout.
#
# Usage: python3 native/enso_quiche/third_party_notices.py QUICHE_SRC > THIRD-PARTY-NOTICES
#
# QUICHE_SRC must hold native/enso_quiche/quiche-Cargo.lock as Cargo.lock
# (cargo fetches the crates it needs). Only crates linked into the library
# on a shipped target are listed: normal dependencies of quiche with the
# ffi feature, without proc-macros or build-only crates.
import json
import os
import subprocess
import sys

TARGETS = [
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
]
FEATURES = "ffi,pkg-config-meta"
LICENSE_PREFIXES = ("LICENSE", "LICENCE", "COPYING", "COPYRIGHT", "NOTICE")
RULE = "-" * 72


def cargo(src, *args):
    return subprocess.run(
        ["cargo", *args], cwd=src, check=True, capture_output=True, text=True
    ).stdout


def linked_packages(src):
    ids = set()
    for target in TARGETS:
        out = cargo(
            src, "tree", "--locked", "-p", "quiche", "--features", FEATURES,
            "-e", "normal,no-proc-macro", "--target", target, "--prefix", "none",
            "--format", "{p}",
        )
        for line in out.splitlines():
            name, version = line.split()[:2]
            ids.add((name, version.lstrip("v")))
    return ids


def license_files(pkg_dir):
    return sorted(
        f for f in os.listdir(pkg_dir)
        if f.upper().startswith(LICENSE_PREFIXES) and os.path.isfile(os.path.join(pkg_dir, f))
    )


def read(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read().rstrip() + "\n"


def main(src):
    meta = json.loads(cargo(src, "metadata", "--locked", "--format-version", "1"))
    wanted = linked_packages(src)
    pkgs = sorted(
        (p for p in meta["packages"] if (p["name"], p["version"]) in wanted),
        key=lambda p: (p["name"], p["version"]),
    )
    out = sys.stdout
    out.write(
        "Third-party software statically linked into the libenso_quiche native\n"
        "library shipped in the enso classifier jars (Rust crates resolved from\n"
        "native/enso_quiche/quiche-Cargo.lock), with their license texts.\n"
        "Generated by native/enso_quiche/third_party_notices.py; do not edit.\n\n"
    )
    out.write("Summary\n\n")
    for p in pkgs:
        out.write(f"  {p['name']} {p['version']}  {p['license'] or 'see below'}\n")
    out.write("  BoringSSL (vendored by boring-sys)  OpenSSL AND SSLeay AND ISC AND MIT\n")
    for p in pkgs:
        pkg_dir = os.path.dirname(p["manifest_path"])
        out.write(f"\n{RULE}\n{p['name']} {p['version']}\n{RULE}\n\n")
        out.write(f"License: {p['license'] or p.get('license_file') or 'unspecified'}\n")
        if p.get("repository"):
            out.write(f"Source: {p['repository']}\n")
        files = license_files(pkg_dir)
        if not files:
            raise SystemExit(f"{p['name']} {p['version']}: no license file in {pkg_dir}")
        for f in files:
            out.write(f"\n---- {f} ----\n\n")
            out.write(read(os.path.join(pkg_dir, f)))
        if p["name"] == "boring-sys":
            boringssl = os.path.join(pkg_dir, "deps", "boringssl", "LICENSE")
            out.write(f"\n{RULE}\nBoringSSL (built from boring-sys {p['version']} deps/boringssl)\n{RULE}\n\n")
            out.write("Source: https://boringssl.googlesource.com/boringssl/\n\n")
            out.write(read(boringssl))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__ or "usage: third_party_notices.py QUICHE_SRC")
    main(sys.argv[1])
