;; ABOUTME: Live-server fuzz tests over raw sockets: HTTP/1.1 request framing (smuggling-shaped
;; ABOUTME: CL/TE, chunk and whitespace mutations) and the WebSocket frame parser.
(ns s-exp.enso-wire-fuzz-test
  "Every trial opens a fresh connection, writes generated bytes (split
  into arbitrary TCP writes) and reads until the server closes. A trial
  fails when the server hangs past its timeouts, emits a malformed
  response/frame, answers a request it had to refuse to read past, or
  answers a pipelined follow-up request incorrectly (desync)."
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is use-fixtures]]
            [clojure.test.check.generators :as gen]
            [clojure.test.check.properties :as prop]
            [s-exp.enso :as enso]
            [s-exp.enso-property-support :as ps])
  (:import (com.s_exp.enso.api WebSocketSocket)
           (java.io ByteArrayOutputStream InputStream OutputStream)
           (java.net InetSocketAddress Socket SocketTimeoutException)
           (java.nio ByteBuffer)
           (java.nio.charset StandardCharsets)
           (java.util Arrays)))

(set! *warn-on-reflection* true)

;; Server timeouts are short so that inputs leaving the server waiting
;; for more bytes resolve quickly; a trial's deadline sits well above them.
(def ^:private server-opts
  {:host "127.0.0.1" :port 0 :idle-timeout 500 :header-timeout 1000 :read-timeout 1000})

(def ^:private trial-deadline-ms 6000)

(def ^:dynamic ^:private *port* nil)

(defn- echo-handler
  "HTTP: answers `<uri>|<body bytes read>`. WebSocket: echoes messages."
  [request]
  (if (= "websocket" (some-> ^String (get-in request [:headers "upgrade"]) .toLowerCase))
    {:ring.websocket/listener
     {:on-message (fn [^WebSocketSocket socket message]
                    (if (instance? CharSequence message)
                      (.sendText socket ^CharSequence message)
                      (.sendBinary socket ^ByteBuffer message)))}}
    (let [n (if-let [^InputStream body (:body request)] (alength (.readAllBytes body)) 0)]
      {:status 200
       :headers {"content-type" "text/plain"}
       :body (str (:uri request) "|" n)})))

(use-fixtures :once
  (fn [f]
    (let [srv (enso/run-server echo-handler server-opts)]
      (try
        (binding [*port* (enso/port srv)]
          (f))
        (finally (enso/stop srv))))))

;; ---- raw connection ------------------------------------------------------------

(defn- exchange!
  "Connects, writes `chunks` (flushing each), then reads until EOF or the
  trial deadline. {:bytes byte[] :eof bool}. A reset counts as EOF."
  [chunks]
  (with-open [sock (Socket.)]
    (.connect sock (InetSocketAddress. "127.0.0.1" (int *port*)) 2000)
    (.setSoTimeout sock 100)
    (let [^OutputStream out (.getOutputStream sock)
          in (.getInputStream sock)
          buf (ByteArrayOutputStream.)
          scratch (byte-array 8192)
          deadline (+ (System/currentTimeMillis) trial-deadline-ms)]
      (try
        (doseq [^bytes c chunks]
          (.write out c)
          (.flush out))
        (catch java.io.IOException _))
      (loop []
        (let [r (try
                  (.read in scratch)
                  (catch SocketTimeoutException _ 0)
                  (catch java.io.IOException _ -1))]
          (cond
            (neg? r) {:bytes (.toByteArray buf) :eof true}
            (> (System/currentTimeMillis) deadline) {:bytes (.toByteArray buf) :eof false}
            :else (do (.write buf scratch 0 (int r)) (recur))))))))

(defn- latin1 ^bytes [^String s] (.getBytes s StandardCharsets/ISO_8859_1))

;; ---- HTTP/1.1 response parsing --------------------------------------------------

(defn- index-of ^long [^bytes hay ^bytes needle ^long from]
  (let [n (alength hay) m (alength needle)]
    (loop [i from]
      (cond
        (> (+ i m) n) -1
        (Arrays/equals hay (int i) (int (+ i m)) needle 0 (int m)) i
        :else (recur (inc i))))))

(def ^:private crlf (latin1 "\r\n"))
(def ^:private crlfcrlf (latin1 "\r\n\r\n"))

(defn- parse-chunked
  "[body end-offset] of a chunked body starting at `off`, or nil."
  [^bytes bs ^long off]
  (loop [off off
         body (ByteArrayOutputStream.)]
    (let [eol (long (index-of bs crlf off))]
      (when-not (neg? eol)
        (let [size-str (first (str/split (String. bs (int off) (int (- eol off)) StandardCharsets/ISO_8859_1) #";"))
              size (long (try (Long/parseLong (str/trim size-str) 16) (catch NumberFormatException _ -1)))]
          (cond
            (neg? size) nil
            (zero? size) (let [end (index-of bs crlfcrlf (- eol 2))]
                           (when-not (neg? end) [(.toByteArray body) (+ end 4)]))
            (> (+ eol 2 size 2) (alength bs)) nil
            :else (do (.write body bs (int (+ eol 2)) (int size))
                      (recur (+ eol 2 size 2) body))))))))

(defn- parse-responses
  "Parses every response in `bs`. {:responses [{:status :headers :body}]
  :malformed reason-or-nil}."
  [^bytes bs]
  (loop [off 0
         out []]
    (if (>= off (alength bs))
      {:responses out}
      (let [end (index-of bs crlfcrlf off)]
        (if (neg? end)
          {:responses out :malformed "incomplete head"}
          (let [head (String. bs (int off) (int (- end off)) StandardCharsets/ISO_8859_1)
                [status-line & header-lines] (str/split head #"\r\n")
                status (some->> status-line (re-matches #"HTTP/1\.1 (\d{3}) [^\r\n]*") second Long/parseLong)
                headers (into {} (map (fn [l] (let [[k v] (str/split l #":\s*" 2)] [(str/lower-case k) (str v)])))
                              header-lines)
                body-off (+ end 4)
                cl (some-> (headers "content-length") Long/parseLong)]
            (cond
              (nil? status) {:responses out :malformed (str "status line " (pr-str status-line))}

              (= "chunked" (headers "transfer-encoding"))
              (if-let [[body next-off] (parse-chunked bs body-off)]
                (recur (long next-off) (conj out {:status status :headers headers :body (String. ^bytes body StandardCharsets/ISO_8859_1)}))
                {:responses out :malformed "bad chunked body"})

              (some? cl)
              (if (> (+ body-off (long cl)) (alength bs))
                {:responses out :malformed "truncated body"}
                (recur (+ body-off (long cl))
                       (conj out {:status status :headers headers
                                  :body (String. bs (int body-off) (int cl) StandardCharsets/ISO_8859_1)})))

              (or (<= 100 status 199) (= 204 status) (= 304 status))
              (recur body-off (conj out {:status status :headers headers :body ""}))

              :else
              {:responses (conj out {:status status :headers headers
                                     :body (String. bs (int body-off) (int (- (alength bs) body-off))
                                                    StandardCharsets/ISO_8859_1)})})))))))

;; ---- HTTP/1.1 request generators ---------------------------------------------------

(def ^:private gen-body (ps/gen-bytes 120))

;; Includes BWS before ";" (RFC 9112 §7.1.1).
(def ^:private gen-chunk-ext
  (gen/elements ["" "" ";a=b" ";ext" ";x=\"q\"" " ;a=b" "\t;ext" "  ;x"]))

(defn- chunked-body
  "Chunked encoding of `body` split at `cuts`, with chunk extensions and
  optional trailer."
  ^bytes [^bytes body cuts exts trailer]
  (let [out (ByteArrayOutputStream.)]
    (doseq [[^bytes chunk ext] (map vector (remove #(zero? (alength ^bytes %)) (ps/split-at-points body cuts))
                                    (cycle exts))]
      (.write out (latin1 (str (Integer/toHexString (alength chunk)) ext "\r\n")))
      (.write out chunk)
      (.write out ^bytes crlf))
    (.write out (latin1 (str "0\r\n" (when trailer "x-trailer: t\r\n") "\r\n")))
    (.toByteArray out)))

(def ^:private gen-valid-request
  ;; [uri bytes]: a well-formed request with a Content-Length or chunked body.
  (gen/let [method (gen/elements ["GET" "POST" "PUT" "DELETE"])
            n (gen/choose 0 99999)
            ^bytes body gen-body
            framing (gen/elements [:none :content-length :chunked])
            cuts (gen/vector gen/nat 0 4)
            exts (gen/vector gen-chunk-ext 1 3)
            trailer gen/boolean
            extra (gen/vector (gen/elements ["Accept: */*\r\n" "X-Pad: a b  c\r\n" "User-Agent: fuzz\r\n"
                                             "Connection: keep-alive\r\n" "x-empty:\r\n"])
                              0 3)]
    (let [uri (str "/r" n)
          framing (if (and (= framing :none) (pos? (alength body))) :content-length framing)
          [framing-header ^bytes payload]
          (case framing
            :none ["" (byte-array 0)]
            :content-length [(str "Content-Length: " (alength body) "\r\n") body]
            :chunked ["Transfer-Encoding: chunked\r\n" (chunked-body body cuts exts trailer)])]
      {:uri uri
       :body-len (if (= framing :none) 0 (alength body))
       :bytes (let [out (ByteArrayOutputStream.)]
                (.write out (latin1 (str method " " uri " HTTP/1.1\r\nHost: localhost\r\n"
                                         (apply str extra) framing-header "\r\n")))
                (.write out payload)
                (.toByteArray out))})))

(def ^:private sentinel
  {:uri "/sentinel"
   :bytes (latin1 "GET /sentinel HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n")})

(def ^:private smuggled
  (latin1 "GET /smuggled HTTP/1.1\r\nHost: localhost\r\n\r\n"))

(defn- concat-bytes ^bytes [& arrays]
  (let [out (ByteArrayOutputStream.)]
    (doseq [^bytes a arrays] (.write out a 0 (alength a)))
    (.toByteArray out)))

(defn- generic-violations
  "Invariants every exchange must satisfy, whatever was sent."
  [{:keys [eof ^bytes bytes]} parsed]
  (let [rs (:responses parsed)
        sentinel-idx (keep-indexed (fn [i r] (when (str/starts-with? (:body r) "/sentinel|") i)) rs)]
    (cond-> []
      (not eof) (conj "server neither closed nor finished within the deadline")
      (:malformed parsed) (conj (str "malformed response: " (:malformed parsed)))
      (some #(not (<= 100 (long (:status %)) 599)) rs) (conj "status out of range")
      (> (count sentinel-idx) 1) (conj "sentinel answered twice")
      (and (seq sentinel-idx) (not= (first sentinel-idx) (dec (count rs)))) (conj "response after the sentinel")
      (and (seq sentinel-idx) (not= "/sentinel|0" (:body (nth rs (first sentinel-idx)))))
      (conj "sentinel answered with a wrong body"))))

(defn- run-exchange [^bytes wire cuts]
  (let [res (exchange! (ps/split-at-points wire cuts))]
    (assoc res :parsed (parse-responses (:bytes res)))))

(defn- report
  "True when `violations` is empty; prints the input otherwise so the
  failing case can be replayed."
  [violations ^bytes wire res]
  (or (empty? violations)
      (do (println "violations:" violations
                   "\nsent:" (pr-str (String. wire StandardCharsets/ISO_8859_1))
                   "\nreceived:" (pr-str (String. ^bytes (:bytes res) StandardCharsets/ISO_8859_1)))
          false)))

(deftest h1-valid-pipelines-are-answered-in-order
  ;; Well-formed pipelined requests (CL, chunked with extensions and
  ;; trailers, no body) are each answered with the right body length,
  ;; then the sentinel closes the connection.
  (ps/check!
   "HTTP/1.1 valid pipelines"
   (prop/for-all [reqs (gen/vector gen-valid-request 1 3)
                  cuts (gen/vector gen/nat 0 6)]
     (let [wire (apply concat-bytes (concat (map :bytes reqs) [(:bytes sentinel)]))
           {:keys [parsed] :as res} (run-exchange wire cuts)
           expected (concat (map #(str (:uri %) "|" (:body-len %)) reqs) ["/sentinel|0"])
           violations (cond-> (generic-violations res parsed)
                        (not= expected (map :body (:responses parsed)))
                        (conj (str "expected bodies " (vec expected)))
                        (not-every? #(= 200 (:status %)) (:responses parsed))
                        (conj "non-200 response"))]
       (report violations wire res)))
   (ps/trials 0.5)))

;; Requests RFC 9112 requires the server to refuse to read past: after
;; answering (with an error, or for CL+TE possibly normally) it MUST close
;; the connection, so neither the smuggled request nor the sentinel may be
;; answered.
(def ^:private must-close-heads
  [;; §6.3: both Transfer-Encoding and Content-Length
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\nContent-Length: 40\r\n\r\n"
   ;; §6.3: invalid / conflicting Content-Length
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: 4\r\nContent-Length: 5\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: 4, 5\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: +4\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: -4\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: 0x4\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: 4 4\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: 99999999999999999999999\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length:\r\n\r\n"
   ;; §6.3: chunked is not the final coding / unknown coding
   "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked, gzip\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: gzip\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: xchunked\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: identity\r\n\r\n"
   ;; §5.1: whitespace between field name and colon
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length : 4\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding : chunked\r\n\r\n"
   ;; §3.2: missing Host
   "POST /x HTTP/1.1\r\nContent-Length: 4\r\n\r\n"])

;; Chunked bodies with invalid framing (§7.1): reading them fails mid-body.
(def ^:private bad-chunked-bodies
  ["zz\r\nGET /\r\n0\r\n\r\n" "-1\r\nabc\r\n0\r\n\r\n" "fffffffffffffffffffff\r\nx\r\n0\r\n\r\n"
   "\r\nabc\r\n0\r\n\r\n" "4\r\nabcdXX\r\n0\r\n\r\n" "4\nabcd\n0\n\n" "4\r\nabc"])

(def ^:private gen-must-close-wire
  (gen/one-of
   [(gen/fmap (fn [[head ^bytes body]] (concat-bytes (latin1 head) body smuggled (:bytes sentinel)))
              (gen/tuple (gen/elements must-close-heads) (ps/gen-bytes 8)))
    (gen/fmap (fn [body]
                (concat-bytes (latin1 (str "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\n\r\n" body))
                              smuggled (:bytes sentinel)))
              (gen/elements bad-chunked-bodies))]))

(deftest h1-ambiguous-framing-closes-the-connection
  (ps/check!
   "HTTP/1.1 smuggling-shaped framing is refused and the connection closed"
   (prop/for-all [^bytes wire gen-must-close-wire
                  cuts (gen/vector gen/nat 0 6)]
     (let [{:keys [parsed] :as res} (run-exchange wire cuts)
           rs (:responses parsed)
           violations (cond-> (generic-violations res parsed)
                        (> (count rs) 1) (conj "answered a request after unrecoverable framing")
                        (some #(str/starts-with? (:body %) "/smuggled") rs) (conj "smuggled request answered"))]
       (report violations wire res)))
   (ps/trials 0.5)))

;; Field-level edge cases the RFC lets a server either reject or repair;
;; only the generic invariants apply.
(def ^:private lenient-heads
  ["GET /x HTTP/1.1\r\nHost: localhost\r\nX-A: a\r\n b\r\n\r\n"
   "GET /x HTTP/1.1\r\nHost: localhost\r\nX-A: a\rb\r\n\r\n"
   "GET /x HTTP/1.1\nHost: localhost\n\n"
   "GET /x HTTP/1.1\r\nHost: localhost\r\n\tX-A: b\r\n\r\n"
   "GET  /x HTTP/1.1\r\nHost: localhost\r\n\r\n"
   "GET /x HTTP/1.1 \r\nHost: localhost\r\n\r\n"
   "GET /x HTTP/1.0\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\n"
   "GET /x\u0000 HTTP/1.1\r\nHost: localhost\r\n\r\n"
   "GET /x HTTP/1.1\r\nHost: localhost\r\nX-\u0000: a\r\n\r\n"
   "\r\n\r\nGET /x HTTP/1.1\r\nHost: localhost\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\n"
   "POST /x HTTP/1.1\r\nHost: localhost\r\nContent-Length: 004\r\n\r\nabcd"
   "GET /x HTTP/1.1\r\nHost: localhost\r\nExpect: 100-continue\r\nContent-Length: 2\r\n\r\nab"])

(def ^:private gen-hostile-wire
  (gen/one-of
   [(gen/fmap (fn [head] (concat-bytes (latin1 head) (:bytes sentinel))) (gen/elements lenient-heads))
    ;; Byte-level mutations of a valid pipeline, sentinel appended intact.
    (gen/fmap (fn [[reqs ms]]
                (concat-bytes (ps/mutate (apply concat-bytes (map :bytes reqs)) ms) (:bytes sentinel)))
              (gen/tuple (gen/vector gen-valid-request 1 2) (gen/vector ps/gen-mutation 1 3)))
    ;; Injected CR/LF/SP/HT/NUL/obs-fold at random offsets.
    (gen/fmap (fn [[^bytes req pos s]]
                (let [p (mod (long pos) (inc (alength req)))]
                  (concat-bytes (Arrays/copyOfRange req 0 (int p)) (latin1 s)
                                (Arrays/copyOfRange req (int p) (alength req)) (:bytes sentinel))))
              (gen/tuple (gen/fmap :bytes gen-valid-request) gen/nat
                         (gen/elements ["\r" "\n" " " "\t" "\u0000" "\r\n " "\r\n\r\n" ":" "\r\nContent-Length: 3\r\n"
                                        "\r\nTransfer-Encoding: chunked\r\n"])))
    (ps/gen-bytes 200)]))

(deftest h1-hostile-requests-never-hang-or-desync
  (ps/check!
   "HTTP/1.1 hostile requests: valid responses or close, no hang, no desync"
   (prop/for-all [^bytes wire gen-hostile-wire
                  cuts (gen/vector gen/nat 0 6)]
     (let [{:keys [parsed] :as res} (run-exchange wire cuts)]
       (report (generic-violations res parsed) wire res)))))

;; ---- WebSocket ----------------------------------------------------------------------

(def ^:private ws-handshake
  (latin1 (str "GET /ws HTTP/1.1\r\nHost: localhost\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n"
               "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\nSec-WebSocket-Version: 13\r\n\r\n")))

(defn- ws-frame
  "Client frame bytes. `mask` nil sends it unmasked."
  ^bytes [{:keys [fin rsv opcode ^bytes payload ^bytes mask]}]
  (let [out (ByteArrayOutputStream.)
        n (alength payload)]
    (.write out (int (bit-or (if fin 0x80 0) (bit-shift-left (long (or rsv 0)) 4) (long opcode))))
    (let [m (if mask 0x80 0)]
      (cond
        (< n 126) (.write out (int (bit-or m n)))
        (< n 65536) (do (.write out (int (bit-or m 126)))
                        (.write out (int (bit-shift-right n 8)))
                        (.write out (int (bit-and n 0xff))))
        :else (do (.write out (int (bit-or m 127)))
                  (dotimes [i 8] (.write out (int (bit-and (bit-shift-right n (* 8 (- 7 i))) 0xff)))))))
    (if mask
      (do (.write out mask)
          (dotimes [i n] (.write out (int (bit-xor (aget payload i) (aget mask (bit-and i 3)))))))
      (.write out payload))
    (.toByteArray out)))

(defn- parse-server-frames
  "Server frames in `bs` after the 101 response head. {:frames [...]
  :malformed reason-or-nil}."
  [^bytes bs]
  (let [start (index-of bs crlfcrlf 0)]
    (if (or (neg? start)
            (not (str/starts-with? (String. bs 0 (int (min 12 (alength bs))) StandardCharsets/ISO_8859_1)
                                   "HTTP/1.1 101")))
      {:frames [] :malformed "no 101 response"}
      (loop [off (+ start 4)
             frames []]
        (if (>= off (alength bs))
          {:frames frames}
          (if (< (- (alength bs) off) 2)
            {:frames frames :malformed "truncated frame header"}
            (let [b0 (bit-and (aget bs off) 0xff)
                  b1 (bit-and (aget bs (inc off)) 0xff)
                  len7 (bit-and b1 0x7f)
                  [len hlen] (case len7
                               126 [(bit-or (bit-shift-left (bit-and (aget bs (+ off 2)) 0xff) 8)
                                            (bit-and (aget bs (+ off 3)) 0xff)) 4]
                               127 [(reduce (fn [^long a i] (bit-or (bit-shift-left a 8) (bit-and (aget bs (+ off 2 (long i))) 0xff)))
                                            0 (range 8)) 10]
                               [len7 2])
                  opcode (bit-and b0 0x0f)
                  end (+ off (long hlen) (long len))]
              (cond
                (not (zero? (bit-and b1 0x80))) {:frames frames :malformed "masked server frame"}
                (not (zero? (bit-and b0 0x70))) {:frames frames :malformed "RSV bits set"}
                (not (#{0 1 2 8 9 10} opcode)) {:frames frames :malformed (str "opcode " opcode)}
                (and (>= opcode 8) (or (> (long len) 125) (zero? (bit-and b0 0x80))))
                {:frames frames :malformed "bad control frame"}
                (> end (alength bs)) {:frames frames :malformed "truncated frame"}
                :else (recur end (conj frames {:fin (not (zero? (bit-and b0 0x80)))
                                               :opcode opcode
                                               :payload (Arrays/copyOfRange bs (int (+ off (long hlen))) (int end))}))))))))))

(defn- server-events
  "Folds server frames into [:message opcode bytes] / [:pong bytes] /
  [:close code]."
  [frames]
  (loop [fs frames
         partial nil
         out []]
    (if-let [{:keys [fin opcode ^bytes payload]} (first fs)]
      (case (long opcode)
        (1 2) (if fin
                (recur (rest fs) nil (conj out [:message opcode (vec payload)]))
                (recur (rest fs) [opcode (vec payload)] out))
        0 (let [[op acc] partial
                acc (into acc payload)]
            (if fin
              (recur (rest fs) nil (conj out [:message op acc]))
              (recur (rest fs) [op acc] out)))
        9 (recur (rest fs) partial (conj out [:ping (vec payload)]))
        10 (recur (rest fs) partial (conj out [:pong (vec payload)]))
        8 (recur (rest fs) partial
                 (conj out [:close (when (>= (alength payload) 2)
                                     (bit-or (bit-shift-left (bit-and (aget payload 0) 0xff) 8)
                                             (bit-and (aget payload 1) 0xff)))])))
      out)))

(def ^:private gen-mask (gen/fmap #(byte-array (map unchecked-byte %)) (gen/vector ps/gen-octet 4)))

(def ^:private gen-text-payload
  (gen/fmap #(.getBytes ^String % StandardCharsets/UTF_8)
            (gen/one-of [gen/string-ascii
                         (gen/fmap #(apply str %) (gen/vector (gen/elements ["é" "ü" "€" "𝄞" "日本" "a" " "]) 0 30))])))

(def ^:private gen-message
  ;; One client message: type, payload, fragmentation cut points, and
  ;; pings interleaved between fragments.
  (gen/let [opcode (gen/elements [1 2])
            ^bytes payload (if (= 1 opcode) gen-text-payload (ps/gen-bytes 300))
            cuts (gen/vector gen/nat 0 3)
            pings (gen/vector (ps/gen-bytes 125) 0 2)
            masks (gen/vector gen-mask 8)]
    {:opcode opcode :payload payload :cuts cuts :pings pings :masks masks}))

(defn- message-frames
  "Client frames for a message from gen-message (pings after the first
  fragment)."
  [{:keys [opcode ^bytes payload cuts pings masks]}]
  (let [chunks (let [cs (vec (ps/split-at-points payload cuts))] (if (empty? cs) [(byte-array 0)] cs))
        n (count chunks)
        data (map-indexed (fn [i c] {:fin (= i (dec n)) :opcode (if (zero? i) opcode 0) :payload c
                                     :mask (nth masks (mod i (count masks)))})
                          chunks)
        ping-frames (map (fn [p m] {:fin true :opcode 9 :payload p :mask m}) pings (reverse masks))]
    (concat (take 1 data) ping-frames (drop 1 data))))

(defn- close-frame [code ^bytes reason ^bytes mask]
  {:fin true :opcode 8 :mask mask
   :payload (concat-bytes (byte-array [(unchecked-byte (bit-shift-right (long code) 8)) (unchecked-byte code)]) reason)})

(defn- ws-exchange [frames cuts]
  (let [wire (apply concat-bytes ws-handshake (map ws-frame frames))
        res (exchange! (ps/split-at-points wire cuts))]
    (assoc res :wire wire :parsed (parse-server-frames (:bytes res)))))

(defn- ws-report [violations {:keys [^bytes wire ^bytes bytes]}]
  (or (empty? violations)
      (do (println "violations:" violations
                   "\nsent (hex):" (apply str (map #(format "%02x" %) wire))
                   "\nreceived (latin1):" (pr-str (String. bytes StandardCharsets/ISO_8859_1)))
          false)))

(defn- echoes [events] (filter #(= :message (first %)) events))

(deftest ws-valid-sequences-are-echoed
  (ps/check!
   "WebSocket: fragmented/masked messages with interleaved pings are echoed, pings ponged, close echoed"
   (prop/for-all [messages (gen/vector gen-message 0 4)
                  mask gen-mask
                  cuts (gen/vector gen/nat 0 8)]
     (let [frames (concat (mapcat message-frames messages) [(close-frame 1000 (byte-array 0) mask)])
           {:keys [eof parsed] :as res} (ws-exchange frames cuts)
           events (server-events (:frames parsed))
           violations (cond-> []
                        (not eof) (conj "no close within the deadline")
                        (:malformed parsed) (conj (str "malformed: " (:malformed parsed)))
                        (not= (map (fn [{:keys [opcode ^bytes payload]}] [:message opcode (vec payload)]) messages)
                              (echoes events))
                        (conj "echoes differ")
                        (not= (frequencies (map vec (mapcat :pings messages)))
                              (frequencies (keep (fn [[k p]] (when (= :pong k) p)) events)))
                        (conj "pongs differ")
                        (not= [:close 1000] (last events)) (conj (str "last event " (pr-str (last events)))))]
       (ws-report violations res)))
   (ps/trials 0.5)))

;; Protocol violations RFC 6455 requires failing the connection for, with
;; the close code the server must send (§7.4.1).
(def ^:private gen-violation
  (gen/let [mask gen-mask
            ^bytes junk (ps/gen-bytes 20)
            big (ps/gen-bytes 300)]
    (gen/elements
     [[1002 [{:fin true :opcode 1 :payload (latin1 "unmasked") :mask nil}]]
      [1002 [{:fin true :rsv 4 :opcode 1 :payload junk :mask mask}]]
      [1002 [{:fin true :opcode 3 :payload junk :mask mask}]]
      [1002 [{:fin true :opcode 0xB :payload junk :mask mask}]]
      [1002 [{:fin true :opcode 9 :payload (concat-bytes big (byte-array 126)) :mask mask}]]
      [1002 [{:fin false :opcode 9 :payload junk :mask mask}]]
      [1002 [{:fin true :opcode 0 :payload junk :mask mask}]]
      [1002 [{:fin false :opcode 2 :payload junk :mask mask} {:fin true :opcode 2 :payload junk :mask mask}]]
      [1002 [{:fin true :opcode 8 :payload (byte-array [3]) :mask mask}]]
      [1002 [(close-frame 1005 (byte-array 0) mask)]]
      [1002 [(close-frame 999 (byte-array 0) mask)]]
      [1002 [(close-frame 1015 (byte-array 0) mask)]]
      [1007 [{:fin true :opcode 1 :payload (byte-array (map unchecked-byte [0xce 0xba 0xe1 0xbd 0xb9 0xce 0xbc 0xce 0xb5 0xed 0xa0 0x80])) :mask mask}]]
      [1007 [{:fin true :opcode 1 :payload (byte-array (map unchecked-byte [0xff 0xfe])) :mask mask}]]
      [1007 [(close-frame 1000 (byte-array (map unchecked-byte [0xc0 0xaf])) mask)]]])))

(deftest ws-protocol-violations-fail-the-connection
  ;; Valid messages, then one violation, then more valid messages: only
  ;; the messages before the violation are echoed, then CLOSE with the
  ;; mandated code, then TCP close.
  (ps/check!
   "WebSocket: protocol violations close with the mandated code after echoing only prior messages"
   (prop/for-all [before (gen/vector gen-message 0 2)
                  [code bad] gen-violation
                  after (gen/vector gen-message 0 2)
                  cuts (gen/vector gen/nat 0 8)]
     (let [frames (concat (mapcat message-frames before) bad (mapcat message-frames after))
           {:keys [eof parsed] :as res} (ws-exchange frames cuts)
           events (server-events (:frames parsed))
           violations (cond-> []
                        (not eof) (conj "no close within the deadline")
                        (:malformed parsed) (conj (str "malformed: " (:malformed parsed)))
                        (not= (map (fn [{:keys [opcode ^bytes payload]}] [:message opcode (vec payload)]) before)
                              (echoes events))
                        (conj "echoes differ")
                        (not= [:close code] (last events)) (conj (str "expected close " code ", got " (pr-str (last events)))))]
       (ws-report violations res)))
   (ps/trials 0.5)))

(deftest ws-garbage-after-handshake-never-hangs
  (ps/check!
   "WebSocket: arbitrary bytes after the handshake end in a close, never a hang or malformed frame"
   (prop/for-all [^bytes junk (gen/one-of [(ps/gen-bytes 300)
                                           (ps/gen-mutated (gen/fmap #(apply concat-bytes (map ws-frame (message-frames %)))
                                                                     gen-message))])
                  cuts (gen/vector gen/nat 0 8)]
     (let [wire (concat-bytes ws-handshake junk)
           res (exchange! (ps/split-at-points wire cuts))
           parsed (parse-server-frames (:bytes res))
           closes (keep (fn [[k c]] (when (= :close k) c)) (server-events (:frames parsed)))
           violations (cond-> []
                        (not (:eof res)) (conj "no close within the deadline")
                        (:malformed parsed) (conj (str "malformed: " (:malformed parsed)))
                        (some #(and % (not (#{1000 1001 1002 1003 1007 1008 1009 1011} %))) closes)
                        (conj (str "unexpected close codes " (vec closes))))]
       (ws-report violations (assoc res :wire wire))))))
