// Generated by jextract

package com.s_exp.enso.quiche.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class quiche_h {

    quiche_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;
    private static final int QUICHE_PROTOCOL_VERSION = (int)1L;
    /**
     * {@snippet lang=c :
     * #define QUICHE_PROTOCOL_VERSION 1
     * }
     */
    public static int QUICHE_PROTOCOL_VERSION() {
        return QUICHE_PROTOCOL_VERSION;
    }
    private static final int QUICHE_MAX_CONN_ID_LEN = (int)20L;
    /**
     * {@snippet lang=c :
     * #define QUICHE_MAX_CONN_ID_LEN 20
     * }
     */
    public static int QUICHE_MAX_CONN_ID_LEN() {
        return QUICHE_MAX_CONN_ID_LEN;
    }
    private static final int QUICHE_MIN_CLIENT_INITIAL_LEN = (int)1200L;
    /**
     * {@snippet lang=c :
     * #define QUICHE_MIN_CLIENT_INITIAL_LEN 1200
     * }
     */
    public static int QUICHE_MIN_CLIENT_INITIAL_LEN() {
        return QUICHE_MIN_CLIENT_INITIAL_LEN;
    }
    private static final int QUICHE_ERR_DONE = (int)-1L;
    /**
     * {@snippet lang=c :
     * enum quiche_error.QUICHE_ERR_DONE = -1
     * }
     */
    public static int QUICHE_ERR_DONE() {
        return QUICHE_ERR_DONE;
    }
    private static final int QUICHE_ERR_BUFFER_TOO_SHORT = (int)-2L;
    /**
     * {@snippet lang=c :
     * enum quiche_error.QUICHE_ERR_BUFFER_TOO_SHORT = -2
     * }
     */
    public static int QUICHE_ERR_BUFFER_TOO_SHORT() {
        return QUICHE_ERR_BUFFER_TOO_SHORT;
    }
    private static final int QUICHE_ERR_UNKNOWN_VERSION = (int)-3L;
    /**
     * {@snippet lang=c :
     * enum quiche_error.QUICHE_ERR_UNKNOWN_VERSION = -3
     * }
     */
    public static int QUICHE_ERR_UNKNOWN_VERSION() {
        return QUICHE_ERR_UNKNOWN_VERSION;
    }

    private static class quiche_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_POINTER    );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *quiche_version()
     * }
     */
    public static FunctionDescriptor quiche_version$descriptor() {
        return quiche_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *quiche_version()
     * }
     */
    public static MethodHandle quiche_version$handle() {
        return quiche_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *quiche_version()
     * }
     */
    public static MemorySegment quiche_version$address() {
        return quiche_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *quiche_version()
     * }
     */
    public static MemorySegment quiche_version() {
        var mh$ = quiche_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_version");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_new {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_POINTER,
            quiche_h.C_INT
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_new");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * quiche_config *quiche_config_new(uint32_t version)
     * }
     */
    public static FunctionDescriptor quiche_config_new$descriptor() {
        return quiche_config_new.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * quiche_config *quiche_config_new(uint32_t version)
     * }
     */
    public static MethodHandle quiche_config_new$handle() {
        return quiche_config_new.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * quiche_config *quiche_config_new(uint32_t version)
     * }
     */
    public static MemorySegment quiche_config_new$address() {
        return quiche_config_new.ADDR;
    }

    /**
     * {@snippet lang=c :
     * quiche_config *quiche_config_new(uint32_t version)
     * }
     */
    public static MemorySegment quiche_config_new(int version) {
        var mh$ = quiche_config_new.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_new", version);
            }
            return (MemorySegment)mh$.invokeExact(version);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_load_cert_chain_from_pem_file {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_load_cert_chain_from_pem_file");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int quiche_config_load_cert_chain_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static FunctionDescriptor quiche_config_load_cert_chain_from_pem_file$descriptor() {
        return quiche_config_load_cert_chain_from_pem_file.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int quiche_config_load_cert_chain_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static MethodHandle quiche_config_load_cert_chain_from_pem_file$handle() {
        return quiche_config_load_cert_chain_from_pem_file.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int quiche_config_load_cert_chain_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static MemorySegment quiche_config_load_cert_chain_from_pem_file$address() {
        return quiche_config_load_cert_chain_from_pem_file.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int quiche_config_load_cert_chain_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static int quiche_config_load_cert_chain_from_pem_file(MemorySegment config, MemorySegment path) {
        var mh$ = quiche_config_load_cert_chain_from_pem_file.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_load_cert_chain_from_pem_file", config, path);
            }
            return (int)mh$.invokeExact(config, path);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_load_priv_key_from_pem_file {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_load_priv_key_from_pem_file");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int quiche_config_load_priv_key_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static FunctionDescriptor quiche_config_load_priv_key_from_pem_file$descriptor() {
        return quiche_config_load_priv_key_from_pem_file.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int quiche_config_load_priv_key_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static MethodHandle quiche_config_load_priv_key_from_pem_file$handle() {
        return quiche_config_load_priv_key_from_pem_file.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int quiche_config_load_priv_key_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static MemorySegment quiche_config_load_priv_key_from_pem_file$address() {
        return quiche_config_load_priv_key_from_pem_file.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int quiche_config_load_priv_key_from_pem_file(quiche_config *config, const char *path)
     * }
     */
    public static int quiche_config_load_priv_key_from_pem_file(MemorySegment config, MemorySegment path) {
        var mh$ = quiche_config_load_priv_key_from_pem_file.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_load_priv_key_from_pem_file", config, path);
            }
            return (int)mh$.invokeExact(config, path);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_application_protos {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_application_protos");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int quiche_config_set_application_protos(quiche_config *config, const uint8_t *protos, size_t protos_len)
     * }
     */
    public static FunctionDescriptor quiche_config_set_application_protos$descriptor() {
        return quiche_config_set_application_protos.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int quiche_config_set_application_protos(quiche_config *config, const uint8_t *protos, size_t protos_len)
     * }
     */
    public static MethodHandle quiche_config_set_application_protos$handle() {
        return quiche_config_set_application_protos.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int quiche_config_set_application_protos(quiche_config *config, const uint8_t *protos, size_t protos_len)
     * }
     */
    public static MemorySegment quiche_config_set_application_protos$address() {
        return quiche_config_set_application_protos.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int quiche_config_set_application_protos(quiche_config *config, const uint8_t *protos, size_t protos_len)
     * }
     */
    public static int quiche_config_set_application_protos(MemorySegment config, MemorySegment protos, long protos_len) {
        var mh$ = quiche_config_set_application_protos.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_application_protos", config, protos, protos_len);
            }
            return (int)mh$.invokeExact(config, protos, protos_len);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_max_idle_timeout {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_max_idle_timeout");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_max_idle_timeout(quiche_config *config, uint64_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_max_idle_timeout$descriptor() {
        return quiche_config_set_max_idle_timeout.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_max_idle_timeout(quiche_config *config, uint64_t v)
     * }
     */
    public static MethodHandle quiche_config_set_max_idle_timeout$handle() {
        return quiche_config_set_max_idle_timeout.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_max_idle_timeout(quiche_config *config, uint64_t v)
     * }
     */
    public static MemorySegment quiche_config_set_max_idle_timeout$address() {
        return quiche_config_set_max_idle_timeout.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_max_idle_timeout(quiche_config *config, uint64_t v)
     * }
     */
    public static void quiche_config_set_max_idle_timeout(MemorySegment config, long v) {
        var mh$ = quiche_config_set_max_idle_timeout.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_max_idle_timeout", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_max_recv_udp_payload_size {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_max_recv_udp_payload_size");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_max_recv_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_max_recv_udp_payload_size$descriptor() {
        return quiche_config_set_max_recv_udp_payload_size.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_max_recv_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static MethodHandle quiche_config_set_max_recv_udp_payload_size$handle() {
        return quiche_config_set_max_recv_udp_payload_size.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_max_recv_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static MemorySegment quiche_config_set_max_recv_udp_payload_size$address() {
        return quiche_config_set_max_recv_udp_payload_size.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_max_recv_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static void quiche_config_set_max_recv_udp_payload_size(MemorySegment config, long v) {
        var mh$ = quiche_config_set_max_recv_udp_payload_size.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_max_recv_udp_payload_size", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_max_send_udp_payload_size {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_max_send_udp_payload_size");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_max_send_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_max_send_udp_payload_size$descriptor() {
        return quiche_config_set_max_send_udp_payload_size.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_max_send_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static MethodHandle quiche_config_set_max_send_udp_payload_size$handle() {
        return quiche_config_set_max_send_udp_payload_size.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_max_send_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static MemorySegment quiche_config_set_max_send_udp_payload_size$address() {
        return quiche_config_set_max_send_udp_payload_size.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_max_send_udp_payload_size(quiche_config *config, size_t v)
     * }
     */
    public static void quiche_config_set_max_send_udp_payload_size(MemorySegment config, long v) {
        var mh$ = quiche_config_set_max_send_udp_payload_size.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_max_send_udp_payload_size", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_initial_max_data {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_initial_max_data");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_data(quiche_config *config, uint64_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_initial_max_data$descriptor() {
        return quiche_config_set_initial_max_data.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_data(quiche_config *config, uint64_t v)
     * }
     */
    public static MethodHandle quiche_config_set_initial_max_data$handle() {
        return quiche_config_set_initial_max_data.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_data(quiche_config *config, uint64_t v)
     * }
     */
    public static MemorySegment quiche_config_set_initial_max_data$address() {
        return quiche_config_set_initial_max_data.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_data(quiche_config *config, uint64_t v)
     * }
     */
    public static void quiche_config_set_initial_max_data(MemorySegment config, long v) {
        var mh$ = quiche_config_set_initial_max_data.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_initial_max_data", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_initial_max_stream_data_bidi_local {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_initial_max_stream_data_bidi_local");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_local(quiche_config *config, uint64_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_initial_max_stream_data_bidi_local$descriptor() {
        return quiche_config_set_initial_max_stream_data_bidi_local.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_local(quiche_config *config, uint64_t v)
     * }
     */
    public static MethodHandle quiche_config_set_initial_max_stream_data_bidi_local$handle() {
        return quiche_config_set_initial_max_stream_data_bidi_local.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_local(quiche_config *config, uint64_t v)
     * }
     */
    public static MemorySegment quiche_config_set_initial_max_stream_data_bidi_local$address() {
        return quiche_config_set_initial_max_stream_data_bidi_local.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_local(quiche_config *config, uint64_t v)
     * }
     */
    public static void quiche_config_set_initial_max_stream_data_bidi_local(MemorySegment config, long v) {
        var mh$ = quiche_config_set_initial_max_stream_data_bidi_local.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_initial_max_stream_data_bidi_local", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_initial_max_stream_data_bidi_remote {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_initial_max_stream_data_bidi_remote");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_remote(quiche_config *config, uint64_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_initial_max_stream_data_bidi_remote$descriptor() {
        return quiche_config_set_initial_max_stream_data_bidi_remote.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_remote(quiche_config *config, uint64_t v)
     * }
     */
    public static MethodHandle quiche_config_set_initial_max_stream_data_bidi_remote$handle() {
        return quiche_config_set_initial_max_stream_data_bidi_remote.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_remote(quiche_config *config, uint64_t v)
     * }
     */
    public static MemorySegment quiche_config_set_initial_max_stream_data_bidi_remote$address() {
        return quiche_config_set_initial_max_stream_data_bidi_remote.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_bidi_remote(quiche_config *config, uint64_t v)
     * }
     */
    public static void quiche_config_set_initial_max_stream_data_bidi_remote(MemorySegment config, long v) {
        var mh$ = quiche_config_set_initial_max_stream_data_bidi_remote.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_initial_max_stream_data_bidi_remote", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_initial_max_stream_data_uni {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_initial_max_stream_data_uni");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_initial_max_stream_data_uni$descriptor() {
        return quiche_config_set_initial_max_stream_data_uni.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static MethodHandle quiche_config_set_initial_max_stream_data_uni$handle() {
        return quiche_config_set_initial_max_stream_data_uni.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static MemorySegment quiche_config_set_initial_max_stream_data_uni$address() {
        return quiche_config_set_initial_max_stream_data_uni.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_stream_data_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static void quiche_config_set_initial_max_stream_data_uni(MemorySegment config, long v) {
        var mh$ = quiche_config_set_initial_max_stream_data_uni.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_initial_max_stream_data_uni", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_initial_max_streams_bidi {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_initial_max_streams_bidi");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_bidi(quiche_config *config, uint64_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_initial_max_streams_bidi$descriptor() {
        return quiche_config_set_initial_max_streams_bidi.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_bidi(quiche_config *config, uint64_t v)
     * }
     */
    public static MethodHandle quiche_config_set_initial_max_streams_bidi$handle() {
        return quiche_config_set_initial_max_streams_bidi.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_bidi(quiche_config *config, uint64_t v)
     * }
     */
    public static MemorySegment quiche_config_set_initial_max_streams_bidi$address() {
        return quiche_config_set_initial_max_streams_bidi.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_bidi(quiche_config *config, uint64_t v)
     * }
     */
    public static void quiche_config_set_initial_max_streams_bidi(MemorySegment config, long v) {
        var mh$ = quiche_config_set_initial_max_streams_bidi.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_initial_max_streams_bidi", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_initial_max_streams_uni {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_initial_max_streams_uni");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_initial_max_streams_uni$descriptor() {
        return quiche_config_set_initial_max_streams_uni.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static MethodHandle quiche_config_set_initial_max_streams_uni$handle() {
        return quiche_config_set_initial_max_streams_uni.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static MemorySegment quiche_config_set_initial_max_streams_uni$address() {
        return quiche_config_set_initial_max_streams_uni.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_initial_max_streams_uni(quiche_config *config, uint64_t v)
     * }
     */
    public static void quiche_config_set_initial_max_streams_uni(MemorySegment config, long v) {
        var mh$ = quiche_config_set_initial_max_streams_uni.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_initial_max_streams_uni", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_set_disable_active_migration {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER,
            quiche_h.C_BOOL
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_set_disable_active_migration");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_set_disable_active_migration(quiche_config *config, bool v)
     * }
     */
    public static FunctionDescriptor quiche_config_set_disable_active_migration$descriptor() {
        return quiche_config_set_disable_active_migration.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_set_disable_active_migration(quiche_config *config, bool v)
     * }
     */
    public static MethodHandle quiche_config_set_disable_active_migration$handle() {
        return quiche_config_set_disable_active_migration.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_set_disable_active_migration(quiche_config *config, bool v)
     * }
     */
    public static MemorySegment quiche_config_set_disable_active_migration$address() {
        return quiche_config_set_disable_active_migration.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_set_disable_active_migration(quiche_config *config, bool v)
     * }
     */
    public static void quiche_config_set_disable_active_migration(MemorySegment config, boolean v) {
        var mh$ = quiche_config_set_disable_active_migration.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_set_disable_active_migration", config, v);
            }
            mh$.invokeExact(config, v);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_config_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_config_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_config_free(quiche_config *config)
     * }
     */
    public static FunctionDescriptor quiche_config_free$descriptor() {
        return quiche_config_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_config_free(quiche_config *config)
     * }
     */
    public static MethodHandle quiche_config_free$handle() {
        return quiche_config_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_config_free(quiche_config *config)
     * }
     */
    public static MemorySegment quiche_config_free$address() {
        return quiche_config_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_config_free(quiche_config *config)
     * }
     */
    public static void quiche_config_free(MemorySegment config) {
        var mh$ = quiche_config_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_config_free", config);
            }
            mh$.invokeExact(config);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_header_info {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_header_info");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int quiche_header_info(const uint8_t *buf, size_t buf_len, size_t dcil, uint32_t *version, uint8_t *type, uint8_t *scid, size_t *scid_len, uint8_t *dcid, size_t *dcid_len, uint8_t *token, size_t *token_len)
     * }
     */
    public static FunctionDescriptor quiche_header_info$descriptor() {
        return quiche_header_info.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int quiche_header_info(const uint8_t *buf, size_t buf_len, size_t dcil, uint32_t *version, uint8_t *type, uint8_t *scid, size_t *scid_len, uint8_t *dcid, size_t *dcid_len, uint8_t *token, size_t *token_len)
     * }
     */
    public static MethodHandle quiche_header_info$handle() {
        return quiche_header_info.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int quiche_header_info(const uint8_t *buf, size_t buf_len, size_t dcil, uint32_t *version, uint8_t *type, uint8_t *scid, size_t *scid_len, uint8_t *dcid, size_t *dcid_len, uint8_t *token, size_t *token_len)
     * }
     */
    public static MemorySegment quiche_header_info$address() {
        return quiche_header_info.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int quiche_header_info(const uint8_t *buf, size_t buf_len, size_t dcil, uint32_t *version, uint8_t *type, uint8_t *scid, size_t *scid_len, uint8_t *dcid, size_t *dcid_len, uint8_t *token, size_t *token_len)
     * }
     */
    public static int quiche_header_info(MemorySegment buf, long buf_len, long dcil, MemorySegment version, MemorySegment type, MemorySegment scid, MemorySegment scid_len, MemorySegment dcid, MemorySegment dcid_len, MemorySegment token, MemorySegment token_len) {
        var mh$ = quiche_header_info.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_header_info", buf, buf_len, dcil, version, type, scid, scid_len, dcid, dcid_len, token, token_len);
            }
            return (int)mh$.invokeExact(buf, buf_len, dcil, version, type, scid, scid_len, dcid, dcid_len, token, token_len);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_accept {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_INT,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_accept");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * quiche_conn *quiche_accept(const uint8_t *scid, size_t scid_len, const uint8_t *odcid, size_t odcid_len, const struct sockaddr *local, socklen_t local_len, const struct sockaddr *peer, socklen_t peer_len, quiche_config *config)
     * }
     */
    public static FunctionDescriptor quiche_accept$descriptor() {
        return quiche_accept.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * quiche_conn *quiche_accept(const uint8_t *scid, size_t scid_len, const uint8_t *odcid, size_t odcid_len, const struct sockaddr *local, socklen_t local_len, const struct sockaddr *peer, socklen_t peer_len, quiche_config *config)
     * }
     */
    public static MethodHandle quiche_accept$handle() {
        return quiche_accept.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * quiche_conn *quiche_accept(const uint8_t *scid, size_t scid_len, const uint8_t *odcid, size_t odcid_len, const struct sockaddr *local, socklen_t local_len, const struct sockaddr *peer, socklen_t peer_len, quiche_config *config)
     * }
     */
    public static MemorySegment quiche_accept$address() {
        return quiche_accept.ADDR;
    }

    /**
     * {@snippet lang=c :
     * quiche_conn *quiche_accept(const uint8_t *scid, size_t scid_len, const uint8_t *odcid, size_t odcid_len, const struct sockaddr *local, socklen_t local_len, const struct sockaddr *peer, socklen_t peer_len, quiche_config *config)
     * }
     */
    public static MemorySegment quiche_accept(MemorySegment scid, long scid_len, MemorySegment odcid, long odcid_len, MemorySegment local, int local_len, MemorySegment peer, int peer_len, MemorySegment config) {
        var mh$ = quiche_accept.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_accept", scid, scid_len, odcid, odcid_len, local, local_len, peer, peer_len, config);
            }
            return (MemorySegment)mh$.invokeExact(scid, scid_len, odcid, odcid_len, local, local_len, peer, peer_len, config);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_negotiate_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_negotiate_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * ssize_t quiche_negotiate_version(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, uint8_t *out, size_t out_len)
     * }
     */
    public static FunctionDescriptor quiche_negotiate_version$descriptor() {
        return quiche_negotiate_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * ssize_t quiche_negotiate_version(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, uint8_t *out, size_t out_len)
     * }
     */
    public static MethodHandle quiche_negotiate_version$handle() {
        return quiche_negotiate_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * ssize_t quiche_negotiate_version(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, uint8_t *out, size_t out_len)
     * }
     */
    public static MemorySegment quiche_negotiate_version$address() {
        return quiche_negotiate_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * ssize_t quiche_negotiate_version(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, uint8_t *out, size_t out_len)
     * }
     */
    public static long quiche_negotiate_version(MemorySegment scid, long scid_len, MemorySegment dcid, long dcid_len, MemorySegment out, long out_len) {
        var mh$ = quiche_negotiate_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_negotiate_version", scid, scid_len, dcid, dcid_len, out, out_len);
            }
            return (long)mh$.invokeExact(scid, scid_len, dcid, dcid_len, out, out_len);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_retry {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_retry");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * ssize_t quiche_retry(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, const uint8_t *new_scid, size_t new_scid_len, const uint8_t *token, size_t token_len, uint32_t version, uint8_t *out, size_t out_len)
     * }
     */
    public static FunctionDescriptor quiche_retry$descriptor() {
        return quiche_retry.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * ssize_t quiche_retry(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, const uint8_t *new_scid, size_t new_scid_len, const uint8_t *token, size_t token_len, uint32_t version, uint8_t *out, size_t out_len)
     * }
     */
    public static MethodHandle quiche_retry$handle() {
        return quiche_retry.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * ssize_t quiche_retry(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, const uint8_t *new_scid, size_t new_scid_len, const uint8_t *token, size_t token_len, uint32_t version, uint8_t *out, size_t out_len)
     * }
     */
    public static MemorySegment quiche_retry$address() {
        return quiche_retry.ADDR;
    }

    /**
     * {@snippet lang=c :
     * ssize_t quiche_retry(const uint8_t *scid, size_t scid_len, const uint8_t *dcid, size_t dcid_len, const uint8_t *new_scid, size_t new_scid_len, const uint8_t *token, size_t token_len, uint32_t version, uint8_t *out, size_t out_len)
     * }
     */
    public static long quiche_retry(MemorySegment scid, long scid_len, MemorySegment dcid, long dcid_len, MemorySegment new_scid, long new_scid_len, MemorySegment token, long token_len, int version, MemorySegment out, long out_len) {
        var mh$ = quiche_retry.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_retry", scid, scid_len, dcid, dcid_len, new_scid, new_scid_len, token, token_len, version, out, out_len);
            }
            return (long)mh$.invokeExact(scid, scid_len, dcid, dcid_len, new_scid, new_scid_len, token, token_len, version, out, out_len);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_version_is_supported {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_BOOL,
            quiche_h.C_INT
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_version_is_supported");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * bool quiche_version_is_supported(uint32_t version)
     * }
     */
    public static FunctionDescriptor quiche_version_is_supported$descriptor() {
        return quiche_version_is_supported.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * bool quiche_version_is_supported(uint32_t version)
     * }
     */
    public static MethodHandle quiche_version_is_supported$handle() {
        return quiche_version_is_supported.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * bool quiche_version_is_supported(uint32_t version)
     * }
     */
    public static MemorySegment quiche_version_is_supported$address() {
        return quiche_version_is_supported.ADDR;
    }

    /**
     * {@snippet lang=c :
     * bool quiche_version_is_supported(uint32_t version)
     * }
     */
    public static boolean quiche_version_is_supported(int version) {
        var mh$ = quiche_version_is_supported.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_version_is_supported", version);
            }
            return (boolean)mh$.invokeExact(version);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_recv {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_recv");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * ssize_t quiche_conn_recv(quiche_conn *conn, uint8_t *buf, size_t buf_len, const quiche_recv_info *info)
     * }
     */
    public static FunctionDescriptor quiche_conn_recv$descriptor() {
        return quiche_conn_recv.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * ssize_t quiche_conn_recv(quiche_conn *conn, uint8_t *buf, size_t buf_len, const quiche_recv_info *info)
     * }
     */
    public static MethodHandle quiche_conn_recv$handle() {
        return quiche_conn_recv.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * ssize_t quiche_conn_recv(quiche_conn *conn, uint8_t *buf, size_t buf_len, const quiche_recv_info *info)
     * }
     */
    public static MemorySegment quiche_conn_recv$address() {
        return quiche_conn_recv.ADDR;
    }

    /**
     * {@snippet lang=c :
     * ssize_t quiche_conn_recv(quiche_conn *conn, uint8_t *buf, size_t buf_len, const quiche_recv_info *info)
     * }
     */
    public static long quiche_conn_recv(MemorySegment conn, MemorySegment buf, long buf_len, MemorySegment info) {
        var mh$ = quiche_conn_recv.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_recv", conn, buf, buf_len, info);
            }
            return (long)mh$.invokeExact(conn, buf, buf_len, info);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_send {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_send");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * ssize_t quiche_conn_send(quiche_conn *conn, uint8_t *out, size_t out_len, quiche_send_info *out_info)
     * }
     */
    public static FunctionDescriptor quiche_conn_send$descriptor() {
        return quiche_conn_send.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * ssize_t quiche_conn_send(quiche_conn *conn, uint8_t *out, size_t out_len, quiche_send_info *out_info)
     * }
     */
    public static MethodHandle quiche_conn_send$handle() {
        return quiche_conn_send.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * ssize_t quiche_conn_send(quiche_conn *conn, uint8_t *out, size_t out_len, quiche_send_info *out_info)
     * }
     */
    public static MemorySegment quiche_conn_send$address() {
        return quiche_conn_send.ADDR;
    }

    /**
     * {@snippet lang=c :
     * ssize_t quiche_conn_send(quiche_conn *conn, uint8_t *out, size_t out_len, quiche_send_info *out_info)
     * }
     */
    public static long quiche_conn_send(MemorySegment conn, MemorySegment out, long out_len, MemorySegment out_info) {
        var mh$ = quiche_conn_send.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_send", conn, out, out_len, out_info);
            }
            return (long)mh$.invokeExact(conn, out, out_len, out_info);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_timeout_as_nanos {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG_LONG,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_timeout_as_nanos");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint64_t quiche_conn_timeout_as_nanos(const quiche_conn *conn)
     * }
     */
    public static FunctionDescriptor quiche_conn_timeout_as_nanos$descriptor() {
        return quiche_conn_timeout_as_nanos.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint64_t quiche_conn_timeout_as_nanos(const quiche_conn *conn)
     * }
     */
    public static MethodHandle quiche_conn_timeout_as_nanos$handle() {
        return quiche_conn_timeout_as_nanos.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint64_t quiche_conn_timeout_as_nanos(const quiche_conn *conn)
     * }
     */
    public static MemorySegment quiche_conn_timeout_as_nanos$address() {
        return quiche_conn_timeout_as_nanos.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint64_t quiche_conn_timeout_as_nanos(const quiche_conn *conn)
     * }
     */
    public static long quiche_conn_timeout_as_nanos(MemorySegment conn) {
        var mh$ = quiche_conn_timeout_as_nanos.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_timeout_as_nanos", conn);
            }
            return (long)mh$.invokeExact(conn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_on_timeout {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_on_timeout");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_conn_on_timeout(quiche_conn *conn)
     * }
     */
    public static FunctionDescriptor quiche_conn_on_timeout$descriptor() {
        return quiche_conn_on_timeout.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_conn_on_timeout(quiche_conn *conn)
     * }
     */
    public static MethodHandle quiche_conn_on_timeout$handle() {
        return quiche_conn_on_timeout.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_conn_on_timeout(quiche_conn *conn)
     * }
     */
    public static MemorySegment quiche_conn_on_timeout$address() {
        return quiche_conn_on_timeout.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_conn_on_timeout(quiche_conn *conn)
     * }
     */
    public static void quiche_conn_on_timeout(MemorySegment conn) {
        var mh$ = quiche_conn_on_timeout.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_on_timeout", conn);
            }
            mh$.invokeExact(conn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_close {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_BOOL,
            quiche_h.C_LONG_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_close");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int quiche_conn_close(quiche_conn *conn, bool app, uint64_t err, const uint8_t *reason, size_t reason_len)
     * }
     */
    public static FunctionDescriptor quiche_conn_close$descriptor() {
        return quiche_conn_close.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int quiche_conn_close(quiche_conn *conn, bool app, uint64_t err, const uint8_t *reason, size_t reason_len)
     * }
     */
    public static MethodHandle quiche_conn_close$handle() {
        return quiche_conn_close.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int quiche_conn_close(quiche_conn *conn, bool app, uint64_t err, const uint8_t *reason, size_t reason_len)
     * }
     */
    public static MemorySegment quiche_conn_close$address() {
        return quiche_conn_close.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int quiche_conn_close(quiche_conn *conn, bool app, uint64_t err, const uint8_t *reason, size_t reason_len)
     * }
     */
    public static int quiche_conn_close(MemorySegment conn, boolean app, long err, MemorySegment reason, long reason_len) {
        var mh$ = quiche_conn_close.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_close", conn, app, err, reason, reason_len);
            }
            return (int)mh$.invokeExact(conn, app, err, reason, reason_len);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_is_established {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_BOOL,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_is_established");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * bool quiche_conn_is_established(const quiche_conn *conn)
     * }
     */
    public static FunctionDescriptor quiche_conn_is_established$descriptor() {
        return quiche_conn_is_established.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * bool quiche_conn_is_established(const quiche_conn *conn)
     * }
     */
    public static MethodHandle quiche_conn_is_established$handle() {
        return quiche_conn_is_established.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * bool quiche_conn_is_established(const quiche_conn *conn)
     * }
     */
    public static MemorySegment quiche_conn_is_established$address() {
        return quiche_conn_is_established.ADDR;
    }

    /**
     * {@snippet lang=c :
     * bool quiche_conn_is_established(const quiche_conn *conn)
     * }
     */
    public static boolean quiche_conn_is_established(MemorySegment conn) {
        var mh$ = quiche_conn_is_established.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_is_established", conn);
            }
            return (boolean)mh$.invokeExact(conn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_is_closed {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_BOOL,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_is_closed");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * bool quiche_conn_is_closed(const quiche_conn *conn)
     * }
     */
    public static FunctionDescriptor quiche_conn_is_closed$descriptor() {
        return quiche_conn_is_closed.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * bool quiche_conn_is_closed(const quiche_conn *conn)
     * }
     */
    public static MethodHandle quiche_conn_is_closed$handle() {
        return quiche_conn_is_closed.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * bool quiche_conn_is_closed(const quiche_conn *conn)
     * }
     */
    public static MemorySegment quiche_conn_is_closed$address() {
        return quiche_conn_is_closed.ADDR;
    }

    /**
     * {@snippet lang=c :
     * bool quiche_conn_is_closed(const quiche_conn *conn)
     * }
     */
    public static boolean quiche_conn_is_closed(MemorySegment conn) {
        var mh$ = quiche_conn_is_closed.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_is_closed", conn);
            }
            return (boolean)mh$.invokeExact(conn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_conn_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_conn_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_conn_free(quiche_conn *conn)
     * }
     */
    public static FunctionDescriptor quiche_conn_free$descriptor() {
        return quiche_conn_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_conn_free(quiche_conn *conn)
     * }
     */
    public static MethodHandle quiche_conn_free$handle() {
        return quiche_conn_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_conn_free(quiche_conn *conn)
     * }
     */
    public static MemorySegment quiche_conn_free$address() {
        return quiche_conn_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_conn_free(quiche_conn *conn)
     * }
     */
    public static void quiche_conn_free(MemorySegment conn) {
        var mh$ = quiche_conn_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_conn_free", conn);
            }
            mh$.invokeExact(conn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_config_new {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_POINTER    );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_config_new");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * quiche_h3_config *quiche_h3_config_new()
     * }
     */
    public static FunctionDescriptor quiche_h3_config_new$descriptor() {
        return quiche_h3_config_new.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * quiche_h3_config *quiche_h3_config_new()
     * }
     */
    public static MethodHandle quiche_h3_config_new$handle() {
        return quiche_h3_config_new.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * quiche_h3_config *quiche_h3_config_new()
     * }
     */
    public static MemorySegment quiche_h3_config_new$address() {
        return quiche_h3_config_new.ADDR;
    }

    /**
     * {@snippet lang=c :
     * quiche_h3_config *quiche_h3_config_new()
     * }
     */
    public static MemorySegment quiche_h3_config_new() {
        var mh$ = quiche_h3_config_new.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_config_new");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_config_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_config_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_h3_config_free(quiche_h3_config *config)
     * }
     */
    public static FunctionDescriptor quiche_h3_config_free$descriptor() {
        return quiche_h3_config_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_h3_config_free(quiche_h3_config *config)
     * }
     */
    public static MethodHandle quiche_h3_config_free$handle() {
        return quiche_h3_config_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_h3_config_free(quiche_h3_config *config)
     * }
     */
    public static MemorySegment quiche_h3_config_free$address() {
        return quiche_h3_config_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_h3_config_free(quiche_h3_config *config)
     * }
     */
    public static void quiche_h3_config_free(MemorySegment config) {
        var mh$ = quiche_h3_config_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_config_free", config);
            }
            mh$.invokeExact(config);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_conn_new_with_transport {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_conn_new_with_transport");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * quiche_h3_conn *quiche_h3_conn_new_with_transport(quiche_conn *quiche_conn, quiche_h3_config *config)
     * }
     */
    public static FunctionDescriptor quiche_h3_conn_new_with_transport$descriptor() {
        return quiche_h3_conn_new_with_transport.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * quiche_h3_conn *quiche_h3_conn_new_with_transport(quiche_conn *quiche_conn, quiche_h3_config *config)
     * }
     */
    public static MethodHandle quiche_h3_conn_new_with_transport$handle() {
        return quiche_h3_conn_new_with_transport.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * quiche_h3_conn *quiche_h3_conn_new_with_transport(quiche_conn *quiche_conn, quiche_h3_config *config)
     * }
     */
    public static MemorySegment quiche_h3_conn_new_with_transport$address() {
        return quiche_h3_conn_new_with_transport.ADDR;
    }

    /**
     * {@snippet lang=c :
     * quiche_h3_conn *quiche_h3_conn_new_with_transport(quiche_conn *quiche_conn, quiche_h3_config *config)
     * }
     */
    public static MemorySegment quiche_h3_conn_new_with_transport(MemorySegment quiche_conn, MemorySegment config) {
        var mh$ = quiche_h3_conn_new_with_transport.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_conn_new_with_transport", quiche_conn, config);
            }
            return (MemorySegment)mh$.invokeExact(quiche_conn, config);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int QUICHE_H3_EVENT_HEADERS = (int)0L;
    /**
     * {@snippet lang=c :
     * enum quiche_h3_event_type.QUICHE_H3_EVENT_HEADERS = 0
     * }
     */
    public static int QUICHE_H3_EVENT_HEADERS() {
        return QUICHE_H3_EVENT_HEADERS;
    }
    private static final int QUICHE_H3_EVENT_DATA = (int)1L;
    /**
     * {@snippet lang=c :
     * enum quiche_h3_event_type.QUICHE_H3_EVENT_DATA = 1
     * }
     */
    public static int QUICHE_H3_EVENT_DATA() {
        return QUICHE_H3_EVENT_DATA;
    }
    private static final int QUICHE_H3_EVENT_FINISHED = (int)2L;
    /**
     * {@snippet lang=c :
     * enum quiche_h3_event_type.QUICHE_H3_EVENT_FINISHED = 2
     * }
     */
    public static int QUICHE_H3_EVENT_FINISHED() {
        return QUICHE_H3_EVENT_FINISHED;
    }
    private static final int QUICHE_H3_EVENT_GOAWAY = (int)3L;
    /**
     * {@snippet lang=c :
     * enum quiche_h3_event_type.QUICHE_H3_EVENT_GOAWAY = 3
     * }
     */
    public static int QUICHE_H3_EVENT_GOAWAY() {
        return QUICHE_H3_EVENT_GOAWAY;
    }
    private static final int QUICHE_H3_EVENT_RESET = (int)4L;
    /**
     * {@snippet lang=c :
     * enum quiche_h3_event_type.QUICHE_H3_EVENT_RESET = 4
     * }
     */
    public static int QUICHE_H3_EVENT_RESET() {
        return QUICHE_H3_EVENT_RESET;
    }
    private static final int QUICHE_H3_EVENT_PRIORITY_UPDATE = (int)5L;
    /**
     * {@snippet lang=c :
     * enum quiche_h3_event_type.QUICHE_H3_EVENT_PRIORITY_UPDATE = 5
     * }
     */
    public static int QUICHE_H3_EVENT_PRIORITY_UPDATE() {
        return QUICHE_H3_EVENT_PRIORITY_UPDATE;
    }

    private static class quiche_h3_conn_poll {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_conn_poll");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int64_t quiche_h3_conn_poll(quiche_h3_conn *conn, quiche_conn *quic_conn, quiche_h3_event **ev)
     * }
     */
    public static FunctionDescriptor quiche_h3_conn_poll$descriptor() {
        return quiche_h3_conn_poll.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int64_t quiche_h3_conn_poll(quiche_h3_conn *conn, quiche_conn *quic_conn, quiche_h3_event **ev)
     * }
     */
    public static MethodHandle quiche_h3_conn_poll$handle() {
        return quiche_h3_conn_poll.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int64_t quiche_h3_conn_poll(quiche_h3_conn *conn, quiche_conn *quic_conn, quiche_h3_event **ev)
     * }
     */
    public static MemorySegment quiche_h3_conn_poll$address() {
        return quiche_h3_conn_poll.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int64_t quiche_h3_conn_poll(quiche_h3_conn *conn, quiche_conn *quic_conn, quiche_h3_event **ev)
     * }
     */
    public static long quiche_h3_conn_poll(MemorySegment conn, MemorySegment quic_conn, MemorySegment ev) {
        var mh$ = quiche_h3_conn_poll.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_conn_poll", conn, quic_conn, ev);
            }
            return (long)mh$.invokeExact(conn, quic_conn, ev);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_event_type {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_event_type");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * enum quiche_h3_event_type quiche_h3_event_type(quiche_h3_event *ev)
     * }
     */
    public static FunctionDescriptor quiche_h3_event_type$descriptor() {
        return quiche_h3_event_type.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * enum quiche_h3_event_type quiche_h3_event_type(quiche_h3_event *ev)
     * }
     */
    public static MethodHandle quiche_h3_event_type$handle() {
        return quiche_h3_event_type.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * enum quiche_h3_event_type quiche_h3_event_type(quiche_h3_event *ev)
     * }
     */
    public static MemorySegment quiche_h3_event_type$address() {
        return quiche_h3_event_type.ADDR;
    }

    /**
     * {@snippet lang=c :
     * enum quiche_h3_event_type quiche_h3_event_type(quiche_h3_event *ev)
     * }
     */
    public static int quiche_h3_event_type(MemorySegment ev) {
        var mh$ = quiche_h3_event_type.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_event_type", ev);
            }
            return (int)mh$.invokeExact(ev);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_event_for_each_header {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_event_for_each_header");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int quiche_h3_event_for_each_header(quiche_h3_event *ev, int (*cb)(uint8_t *, size_t, uint8_t *, size_t, void *), void *argp)
     * }
     */
    public static FunctionDescriptor quiche_h3_event_for_each_header$descriptor() {
        return quiche_h3_event_for_each_header.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int quiche_h3_event_for_each_header(quiche_h3_event *ev, int (*cb)(uint8_t *, size_t, uint8_t *, size_t, void *), void *argp)
     * }
     */
    public static MethodHandle quiche_h3_event_for_each_header$handle() {
        return quiche_h3_event_for_each_header.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int quiche_h3_event_for_each_header(quiche_h3_event *ev, int (*cb)(uint8_t *, size_t, uint8_t *, size_t, void *), void *argp)
     * }
     */
    public static MemorySegment quiche_h3_event_for_each_header$address() {
        return quiche_h3_event_for_each_header.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int quiche_h3_event_for_each_header(quiche_h3_event *ev, int (*cb)(uint8_t *, size_t, uint8_t *, size_t, void *), void *argp)
     * }
     */
    public static int quiche_h3_event_for_each_header(MemorySegment ev, MemorySegment cb, MemorySegment argp) {
        var mh$ = quiche_h3_event_for_each_header.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_event_for_each_header", ev, cb, argp);
            }
            return (int)mh$.invokeExact(ev, cb, argp);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_event_headers_has_more_frames {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_BOOL,
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_event_headers_has_more_frames");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * bool quiche_h3_event_headers_has_more_frames(quiche_h3_event *ev)
     * }
     */
    public static FunctionDescriptor quiche_h3_event_headers_has_more_frames$descriptor() {
        return quiche_h3_event_headers_has_more_frames.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * bool quiche_h3_event_headers_has_more_frames(quiche_h3_event *ev)
     * }
     */
    public static MethodHandle quiche_h3_event_headers_has_more_frames$handle() {
        return quiche_h3_event_headers_has_more_frames.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * bool quiche_h3_event_headers_has_more_frames(quiche_h3_event *ev)
     * }
     */
    public static MemorySegment quiche_h3_event_headers_has_more_frames$address() {
        return quiche_h3_event_headers_has_more_frames.ADDR;
    }

    /**
     * {@snippet lang=c :
     * bool quiche_h3_event_headers_has_more_frames(quiche_h3_event *ev)
     * }
     */
    public static boolean quiche_h3_event_headers_has_more_frames(MemorySegment ev) {
        var mh$ = quiche_h3_event_headers_has_more_frames.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_event_headers_has_more_frames", ev);
            }
            return (boolean)mh$.invokeExact(ev);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_event_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_event_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_h3_event_free(quiche_h3_event *ev)
     * }
     */
    public static FunctionDescriptor quiche_h3_event_free$descriptor() {
        return quiche_h3_event_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_h3_event_free(quiche_h3_event *ev)
     * }
     */
    public static MethodHandle quiche_h3_event_free$handle() {
        return quiche_h3_event_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_h3_event_free(quiche_h3_event *ev)
     * }
     */
    public static MemorySegment quiche_h3_event_free$address() {
        return quiche_h3_event_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_h3_event_free(quiche_h3_event *ev)
     * }
     */
    public static void quiche_h3_event_free(MemorySegment ev) {
        var mh$ = quiche_h3_event_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_event_free", ev);
            }
            mh$.invokeExact(ev);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_send_response {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_INT,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_BOOL
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_send_response");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int quiche_h3_send_response(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const quiche_h3_header *headers, size_t headers_len, bool fin)
     * }
     */
    public static FunctionDescriptor quiche_h3_send_response$descriptor() {
        return quiche_h3_send_response.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int quiche_h3_send_response(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const quiche_h3_header *headers, size_t headers_len, bool fin)
     * }
     */
    public static MethodHandle quiche_h3_send_response$handle() {
        return quiche_h3_send_response.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int quiche_h3_send_response(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const quiche_h3_header *headers, size_t headers_len, bool fin)
     * }
     */
    public static MemorySegment quiche_h3_send_response$address() {
        return quiche_h3_send_response.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int quiche_h3_send_response(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const quiche_h3_header *headers, size_t headers_len, bool fin)
     * }
     */
    public static int quiche_h3_send_response(MemorySegment conn, MemorySegment quic_conn, long stream_id, MemorySegment headers, long headers_len, boolean fin) {
        var mh$ = quiche_h3_send_response.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_send_response", conn, quic_conn, stream_id, headers, headers_len, fin);
            }
            return (int)mh$.invokeExact(conn, quic_conn, stream_id, headers, headers_len, fin);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_send_body {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG,
            quiche_h.C_BOOL
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_send_body");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * ssize_t quiche_h3_send_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const uint8_t *body, size_t body_len, bool fin)
     * }
     */
    public static FunctionDescriptor quiche_h3_send_body$descriptor() {
        return quiche_h3_send_body.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * ssize_t quiche_h3_send_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const uint8_t *body, size_t body_len, bool fin)
     * }
     */
    public static MethodHandle quiche_h3_send_body$handle() {
        return quiche_h3_send_body.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * ssize_t quiche_h3_send_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const uint8_t *body, size_t body_len, bool fin)
     * }
     */
    public static MemorySegment quiche_h3_send_body$address() {
        return quiche_h3_send_body.ADDR;
    }

    /**
     * {@snippet lang=c :
     * ssize_t quiche_h3_send_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, const uint8_t *body, size_t body_len, bool fin)
     * }
     */
    public static long quiche_h3_send_body(MemorySegment conn, MemorySegment quic_conn, long stream_id, MemorySegment body, long body_len, boolean fin) {
        var mh$ = quiche_h3_send_body.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_send_body", conn, quic_conn, stream_id, body, body_len, fin);
            }
            return (long)mh$.invokeExact(conn, quic_conn, stream_id, body, body_len, fin);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_recv_body {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            quiche_h.C_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_POINTER,
            quiche_h.C_LONG_LONG,
            quiche_h.C_POINTER,
            quiche_h.C_LONG
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_recv_body");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * ssize_t quiche_h3_recv_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, uint8_t *out, size_t out_len)
     * }
     */
    public static FunctionDescriptor quiche_h3_recv_body$descriptor() {
        return quiche_h3_recv_body.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * ssize_t quiche_h3_recv_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, uint8_t *out, size_t out_len)
     * }
     */
    public static MethodHandle quiche_h3_recv_body$handle() {
        return quiche_h3_recv_body.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * ssize_t quiche_h3_recv_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, uint8_t *out, size_t out_len)
     * }
     */
    public static MemorySegment quiche_h3_recv_body$address() {
        return quiche_h3_recv_body.ADDR;
    }

    /**
     * {@snippet lang=c :
     * ssize_t quiche_h3_recv_body(quiche_h3_conn *conn, quiche_conn *quic_conn, uint64_t stream_id, uint8_t *out, size_t out_len)
     * }
     */
    public static long quiche_h3_recv_body(MemorySegment conn, MemorySegment quic_conn, long stream_id, MemorySegment out, long out_len) {
        var mh$ = quiche_h3_recv_body.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_recv_body", conn, quic_conn, stream_id, out, out_len);
            }
            return (long)mh$.invokeExact(conn, quic_conn, stream_id, out, out_len);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class quiche_h3_conn_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            quiche_h.C_POINTER
        );

        public static final MemorySegment ADDR = quiche_h.findOrThrow("quiche_h3_conn_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void quiche_h3_conn_free(quiche_h3_conn *conn)
     * }
     */
    public static FunctionDescriptor quiche_h3_conn_free$descriptor() {
        return quiche_h3_conn_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void quiche_h3_conn_free(quiche_h3_conn *conn)
     * }
     */
    public static MethodHandle quiche_h3_conn_free$handle() {
        return quiche_h3_conn_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void quiche_h3_conn_free(quiche_h3_conn *conn)
     * }
     */
    public static MemorySegment quiche_h3_conn_free$address() {
        return quiche_h3_conn_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void quiche_h3_conn_free(quiche_h3_conn *conn)
     * }
     */
    public static void quiche_h3_conn_free(MemorySegment conn) {
        var mh$ = quiche_h3_conn_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("quiche_h3_conn_free", conn);
            }
            mh$.invokeExact(conn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

