// Generated by jextract

package com.s_exp.enso.quiche.ffm;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * int (*cb)(uint8_t *, size_t, uint8_t *, size_t, void *)
 * }
 */
public class quiche_h3_event_for_each_header$cb {

    quiche_h3_event_for_each_header$cb() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment _x0, long _x1, MemorySegment _x2, long _x3, MemorySegment _x4);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        quiche_h.C_INT,
        quiche_h.C_POINTER,
        quiche_h.C_LONG,
        quiche_h.C_POINTER,
        quiche_h.C_LONG,
        quiche_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = quiche_h.upcallHandle(quiche_h3_event_for_each_header$cb.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(quiche_h3_event_for_each_header$cb.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1, MemorySegment _x2, long _x3, MemorySegment _x4) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

